// Jitsi Meet configuration for Flutter client
// WARNING: Never store Jitsi JWT secrets or generate tokens client-side!
// All JWT tokens must be provided by the backend.
import 'dart:io' show Platform;

class JitsiConfig {
  // Self-hosted Jitsi Meet server URL
  // Android emulator cannot use localhost; use 10.0.2.2 to reach host
  // For real device, use your computer's IP address
  // Configure via --dart-define=JITSI_SERVER=http://YOUR_IP:8000
  static String get serverUrl {
    const jitsiServer = String.fromEnvironment(
      'JITSI_SERVER',
      defaultValue: 'http://10.0.2.2:8000', // Default for emulator
    );
    return jitsiServer;
  }
  
  // Note: JWT tokens are generated by the backend using JITSI_APP_SECRET
  // and must be signed with the same secret configured in your Jitsi server
}

