// Jitsi Meet configuration for Flutter client
// WARNING: Never store Jitsi JWT secrets or generate tokens client-side!
// All JWT tokens must be provided by the backend.
import 'dart:io' show Platform;

class JitsiConfig {
  // Self-hosted Jitsi Meet server URL
  // Android emulator cannot use localhost; use 10.0.2.2 to reach host
  static String get serverUrl {
    if (Platform.isAndroid) return 'http://10.0.2.2:8000';
    return 'http://localhost:8000';
  }
  
  // Note: JWT tokens are generated by the backend using JITSI_APP_SECRET
  // and must be signed with the same secret configured in your Jitsi server
}

